spring.application.name=auth-service
spring.flyway.enabled=true
# spring.datasource.url=jdbc:postgresql://localhost:5438/deseases
spring.datasource.url=jdbc:postgresql://postgres:5432/deseases
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8090

app.jwtSecret=9d52c1c5835d0525092cb78340711cb14b4e55672411808d37d57b05d5159401
app.jwtExpirationMs=86400000
app.jwtRefreshExpirationMs=1209600000

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
# eureka.instance.hostname=auth-service